{% set name = "aimsim" %}
{% set version = "2.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aimsim-{{ version }}.tar.gz
  sha256: 437c8a2d54901affef45be50a187eea0c3cf47e5b26a886d7f3b30f33e1b0c3d

build:
  entry_points:
    - aimsim=aimsim.__main__:start_AIMSim
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - scipy
    - matplotlib-base
    - seaborn
    - tabulate
    - numpy
    - multiprocess >=0.70
    - scikit-learn-extra
    - pandas
    - pyyaml >=5
    - scikit-learn
    - rdkit
    - psutil
    - padelpy
    - plotly
    - mhfp
    - darkdetect
    - mordredcommunity
    - openpyxl

test:
  imports:
    - aimsim
    - interfaces
  commands:
    - aimsim --help
  requires:
    - pip

about:
  home: https://github.com/VlachosGroup/AIMSim
  summary: Python command line and GUI tool to analyze molecular similarity.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - JacksonBurns
